apiVersion: 1

datasources:
  - name: InfluxDB_v2_Flux
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    uid: ambient-influxdb
    jsonData:
      version: Flux
      organization: homeiot
      defaultBucket: sensors
      tlsSkipVerify: true
    secureJsonData:
      token: $INFLUXDB_TOKEN